# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayıt_sayfası.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class kayit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 597)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 401, 591))
        self.textEdit.setStyleSheet("background-color:rgb(6, 61, 150)")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 470, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{color:white;background-color:rgb(14, 207, 104);border:none;border-radius:20px;}\n"
"QPushButton::hover{background-color:black;}\n"
"QPushButton::focus{background-color:black;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.kullanici_3 = QtWidgets.QLineEdit(Form)
        self.kullanici_3.setGeometry(QtCore.QRect(100, 220, 201, 41))
        self.kullanici_3.setStyleSheet("background-color:rgb(0, 206, 247);border:none;border-radius:20px;color:white;padding-left:20px;\n"
"")
        self.kullanici_3.setText("")
        self.kullanici_3.setObjectName("kullanici_3")
        self.kullanici = QtWidgets.QLineEdit(Form)
        self.kullanici.setGeometry(QtCore.QRect(100, 300, 201, 41))
        self.kullanici.setStyleSheet("background-color:rgb(0, 206, 247);border:none;border-radius:20px;color:white;padding-left:20px;\n"
"")
        self.kullanici.setText("")
        self.kullanici.setObjectName("kullanici")
        self.kullanici_2 = QtWidgets.QLineEdit(Form)
        self.kullanici_2.setGeometry(QtCore.QRect(100, 380, 201, 41))
        self.kullanici_2.setStyleSheet("background-color:rgb(0, 206, 247);border:none;border-radius:20px;color:white;padding-left:20px;\n"
"")
        self.kullanici_2.setText("")
        self.kullanici_2.setObjectName("kullanici_2")
        self.kullanici_4 = QtWidgets.QLineEdit(Form)
        self.kullanici_4.setGeometry(QtCore.QRect(100, 140, 201, 41))
        self.kullanici_4.setStyleSheet("background-color:rgb(0, 206, 247);border:none;border-radius:20px;color:white;padding-left:20px;\n"
"")
        self.kullanici_4.setText("")
        self.kullanici_4.setObjectName("kullanici_4")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(80, 40, 241, 51))
        self.textEdit_2.setStyleSheet("background-color:rgb(14, 207, 104);border:none;border-radius:20px;color:white;padding-left:20px;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(150, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 270, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(170, 350, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white")
        self.label_4.setObjectName("label_4")
        self.baslik = QtWidgets.QLabel(Form)
        self.baslik.setGeometry(QtCore.QRect(110, 20, 181, 91))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        self.baslik.setFont(font)
        self.baslik.setStyleSheet("color:white")
        self.baslik.setObjectName("baslik")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "KayıtOl"))
        self.label_3.setText(_translate("Form", "İsim-Soyisim"))
        self.label.setText(_translate("Form", "Yaş"))
        self.label_2.setText(_translate("Form", "OkuduğuOkul"))
        self.label_4.setText(_translate("Form", "Mail"))
        self.baslik.setText(_translate("Form", "KAYIT SAYFASI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = kayit()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
