# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page_yeni.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class login(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(380, 659)
        self.bg1 = QtWidgets.QLabel(Form)
        self.bg1.setGeometry(QtCore.QRect(0, 0, 381, 661))
        self.bg1.setStyleSheet("background-color:rgb(6, 61, 150)")
        self.bg1.setText("")
        self.bg1.setObjectName("bg1")
        self.bg2 = QtWidgets.QLabel(Form)
        self.bg2.setGeometry(QtCore.QRect(20, 20, 341, 621))
        self.bg2.setStyleSheet("background-color:rgb(14, 207, 104)")
        self.bg2.setText("")
        self.bg2.setObjectName("bg2")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(70, 90, 241, 51))
        self.textEdit.setStyleSheet("background-color:rgb(6, 61, 150);border:none;border-radius:20px;color:white;padding-left:20px;")
        self.textEdit.setObjectName("textEdit")
        self.baslik = QtWidgets.QLabel(Form)
        self.baslik.setGeometry(QtCore.QRect(100, 70, 181, 91))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        self.baslik.setFont(font)
        self.baslik.setStyleSheet("color:white")
        self.baslik.setObjectName("baslik")
        self.kullanici = QtWidgets.QLineEdit(Form)
        self.kullanici.setGeometry(QtCore.QRect(90, 220, 201, 41))
        self.kullanici.setStyleSheet("background-color:rgb(0, 206, 247);border:none;border-radius:20px;color:white;padding-left:20px;\n"
"")
        self.kullanici.setText("")
        self.kullanici.setObjectName("kullanici")
        self.kullanici_2 = QtWidgets.QLineEdit(Form)
        self.kullanici_2.setGeometry(QtCore.QRect(90, 310, 201, 41))
        self.kullanici_2.setStyleSheet("background-color:rgb(0, 206, 247);border:none;border-radius:20px;color:white;padding-left:20px;\n"
"")
        self.kullanici_2.setText("")
        self.kullanici_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.kullanici_2.setObjectName("kullanici_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 400, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{color:white;background-color:rgb(6, 61, 150);border:none;border-radius:20px;}\n"
"QPushButton::hover{background-color:black;}\n"
"QPushButton::focus{background-color:black;}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 280, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.baslik.setText(_translate("Form", "GİRİŞ SAYFASI"))
        self.pushButton.setText(_translate("Form", "GirişYap"))
        self.label.setText(_translate("Form", "Kullanıcı Adı"))
        self.label_2.setText(_translate("Form", "        Şifre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = login()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
